#!/usr/bin/env bash
# ******************************************************
# Author       : kaleo
# Last modified: 2016-12-17 12:42
# Email        : kaleo1990@hotmail.com
# Filename     : push.sh
# Description  : 
# *****************************************************
git push
