#!/usr/bin/env bash
# ******************************************************
# Author       : kaleo
# Last modified: 2016-12-31 13:51
# Email        : kaleo1990@hotmail.com
# Filename     : updateconfig
# Description  : 
# ******************************************************
if [[ $3x=x ]]; then
echo "update homestead.sysconfigs set value='$2' where name='$1';"|mysql -h127.0.0.1 -uhomestead -psecret
else
echo "update homestead.sysconfigs set value='$2' where name='$1';"|mysql -h$3 -uhomestead -psecret
fi
echo "select * from homestead.sysconfigs ;"|mysql -h$3 -uhomestead -psecret
